### ISSUE TITLE
table of records support

### ISSUE THREAD

**Issue by smnbbrv** [tgulacsi/oracall#2]
Hi,

your project is absolutely awesome!

We tried to generate various things and found out that the record arrays are not supported

```plsql
  type test_record is record(
    strName varchar2(4000),
    boolName boolean,
    intName integer
  );

  type test_array is table of test_record index by pls_integer;

  function func(records test_array) return varchar2;
```

This gives the following error:

> panic: ORA_CALL.func: nonsense table type of records IN SCHEMA.ORA_CALL.FUNC[ IN SCHEMA.ORA_CALL.TEST_RECORD{[strname IN VARCHAR2 boolname IN PL/SQL BOOLEAN intname IN INTEGER]}]

So, it recognizes the record, but the generation is stopped.

Is there a reason behind (OCI limitation etc.) or this is just not implemented yet?

Thank you in advance

**Comment by tgulacsi** [comment]
Can you try it without the BOOLEAN ?

**Comment by smnbbrv** [comment]
Sure, will do tomorrow. However it works with Boolean if it's just a record (not a table one)
